language: python

sudo: false

matrix:
  fast_finish: true
  include:
   - env: TOXENV=py34-dj111-wagtail22
     python: 3.4
   - env: TOXENV=py34-dj111-wagtail23
     python: 3.4
   - env: TOXENV=py34-dj20-wagtail22
     python: 3.4
   - env: TOXENV=py34-dj20-wagtail23
     python: 3.4
   - env: TOXENV=py35-dj111-wagtail22
     python: 3.5
   - env: TOXENV=py35-dj111-wagtail23
     python: 3.5
   - env: TOXENV=py35-dj20-wagtail22
     python: 3.5
   - env: TOXENV=py35-dj20-wagtail23
     python: 3.5
   - env: TOXENV=py35-dj21-wagtail23
     python: 3.5
   - env: TOXENV=py36-dj111-wagtail22
     python: 3.6
   - env: TOXENV=py36-dj111-wagtail23
     python: 3.6
   - env: TOXENV=py36-dj20-wagtail22
     python: 3.6
   - env: TOXENV=py36-dj20-wagtail23
     python: 3.6
   - env: TOXENV=py36-dj21-wagtail23
     python: 3.6
   - env: TOXENV=flake8
     python: 3.5
   - env: TOXENV=docs
     python: 3.5


install:
  - pip install tox

script:
  - tox
