site_name: wagtailmodelchooser
site_description: Wagtail chooser panel generator for generic Django models
repo_url: https://github.com/Naeka/wagtailmodelchooser
site_dir: docs-build/html
theme: readthedocs
